
from langchain_core.tools import tool
from utils.decorators import log_execution
from utils.embeddings import vector_store
from config.wrapperConfig import LLMFactory
from langchain_core.prompts import ChatPromptTemplate
import json


from pydantic import BaseModel
from pydantic import BaseModel

class Reference(BaseModel):
    document: str
    page: int

class FinalResponse(BaseModel):
    response: str
    references: list[Reference]

@tool
@log_execution
def handle_fetch(query: str):
    """Fetch relevant information from the PDF knowledge base and generate an answer.
    
    This tool retrieves documents from the vector database related to a user query
    and uses an LLM to generate a comprehensive answer based on that context.
    
    Use this tool whenever:
    - A user asks a question that needs information lookup
    - You need to provide answers based on documents
    - The query requires consulting the knowledge base
    
    Args:
        query: The user's question or search query
        
    Returns:
        A comprehensive answer generated by the LLM based on relevant documents
    """
    try:
        retriever = vector_store.as_retriever(
            search_type="mmr",
            search_kwargs={
                "k": 8,
                "fetch_k": 20
            })

        results = retriever.invoke(query)


        # for i, doc in enumerate(results):
        #     print(f"\n=== RESULT {i+1} ===")
        #     print(doc.metadata)
        #     print(doc.page_content[:1000])

        print(f"Retrieved {len(results)} relevant documents for the query.")
        
        if not results:
            return "No relevant documents found for the query."
        
        context = "\n\n".join([
            f"[Source: {doc.metadata.get('source', 'unknown')}, "
            f"Page: {doc.metadata.get('page', 'unknown')}]\n"
            f"{doc.page_content}"
            for doc in results
        ])
        
        llm = LLMFactory.get_llm()
        
        prompt = ChatPromptTemplate.from_template("""
            You are a helpful assistant.

            Answer ONLY from the provided context.

            Return:
            - response: the answer
            - references: ONLY the document/page combinations actually used to answer

            Do not include pages that were merely retrieved.

            Context:
            {context}

            Question:
            {question}
            """)
        
        llm = LLMFactory.get_llm().with_structured_output(FinalResponse)

        chain = prompt | llm
        response = chain.invoke({
            "context": context,
            "question": query
        })

        return {
            "response": response.response,
            "references": [
                {
                    "document": ref.document,
                    "page": ref.page
                }
                for ref in response.references
            ]
        }
    
    except Exception as e:
        return f"Error in RAG pipeline: {str(e)}"


tools = [handle_fetch]