
from langchain_core.tools import tool
from utils.decorators import log_execution
from utils.embeddings import vector_store
from config.wrapperConfig import LLMFactory
from langchain_core.prompts import ChatPromptTemplate


@tool
@log_execution
def handle_fetch(query: str):
    """Fetch relevant information from the PDF knowledge base and generate an answer.
    
    This tool retrieves documents from the vector database related to a user query
    and uses an LLM to generate a comprehensive answer based on that context.
    
    Use this tool whenever:
    - A user asks a question that needs information lookup
    - You need to provide answers based on documents
    - The query requires consulting the knowledge base
    
    Args:
        query: The user's question or search query
        
    Returns:
        A comprehensive answer generated by the LLM based on relevant documents
    """
    try:
        results = vector_store.similarity_search(query, k=4)

        print(f"Retrieved {len(results)} relevant documents for the query.")
        
        if not results:
            return "No relevant documents found for the query."
        
        context = "\n\n".join([
            f"Source: {doc.metadata.get('source', 'unknown')}\n{doc.page_content}"
            for doc in results
        ])
        
        llm = LLMFactory.get_llm()
        
        prompt = ChatPromptTemplate.from_template("""
                                                  
        You are a helpful assistant. Based on the following context from documents, answer the user's question.

        Context:
        {context}

        Question: {question}

        Provide a comprehensive answer based only on the provided context. If the context doesn't contain enough information to answer, say so.""")
        
        chain = prompt | llm
        
        response = chain.invoke({
            "context": context,
            "question": query
        })
        
        answer = response.content if hasattr(response, 'content') else str(response)
        
        return answer
        
    except Exception as e:
        return f"Error in RAG pipeline: {str(e)}"


tools = [handle_fetch]